/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContractStatus = IDL.Variant({
  'active' : IDL.Null,
  'terminated' : IDL.Null,
  'expired' : IDL.Null,
  'underReview' : IDL.Null,
  'draft' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const ContractInput = IDL.Record({
  'status' : ContractStatus,
  'endDate' : IDL.Int,
  'value' : IDL.Float64,
  'createdBy' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'counterpartyId' : IDL.Text,
  'autoRenew' : IDL.Bool,
  'department' : IDL.Text,
  'riskLevel' : RiskLevel,
  'renewalDate' : IDL.Opt(IDL.Int),
  'startDate' : IDL.Int,
});
export const CounterpartyType = IDL.Variant({
  'client' : IDL.Null,
  'internal' : IDL.Null,
  'regulator' : IDL.Null,
  'vendor' : IDL.Null,
  'partner' : IDL.Null,
});
export const CounterpartyStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'blacklisted' : IDL.Null,
});
export const ObligationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
  'waived' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const ContractTag = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'usageCount' : IDL.Nat,
});
export const ApprovalStep = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'skipped' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'approverRole' : IDL.Text,
  'stepOrder' : IDL.Nat,
  'comments' : IDL.Opt(IDL.Text),
  'decidedAt' : IDL.Opt(IDL.Int),
  'workflowId' : IDL.Nat,
});
export const ApprovalWorkflow = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'contractId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Contract = IDL.Record({
  'id' : IDL.Text,
  'status' : ContractStatus,
  'endDate' : IDL.Int,
  'value' : IDL.Float64,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'currency' : IDL.Text,
  'counterpartyId' : IDL.Text,
  'autoRenew' : IDL.Bool,
  'department' : IDL.Text,
  'riskLevel' : RiskLevel,
  'renewalDate' : IDL.Opt(IDL.Int),
  'startDate' : IDL.Int,
});
export const Counterparty = IDL.Record({
  'id' : IDL.Text,
  'status' : CounterpartyStatus,
  'contactName' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'counterpartyType' : CounterpartyType,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'riskLevel' : RiskLevel,
});
export const TimelineEvent = IDL.Record({
  'id' : IDL.Nat,
  'metadata' : IDL.Opt(IDL.Text),
  'responsibleParty' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'contractId' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileReference = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const Obligation = IDL.Record({
  'id' : IDL.Nat,
  'status' : ObligationStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'priority' : Priority,
  'contractId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createApprovalStep' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'createApprovalWorkflow' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createContract' : IDL.Func([IDL.Text, ContractInput], [], []),
  'createCounterparty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CounterpartyType,
        CounterpartyStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        RiskLevel,
      ],
      [],
      [],
    ),
  'createObligation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        ObligationStatus,
        Priority,
      ],
      [],
      [],
    ),
  'createTag' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createTimelineEvent' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'deleteApprovalStep' : IDL.Func([IDL.Nat], [], []),
  'deleteApprovalWorkflow' : IDL.Func([IDL.Nat], [], []),
  'deleteContract' : IDL.Func([IDL.Text], [], []),
  'deleteCounterparty' : IDL.Func([IDL.Text], [], []),
  'deleteFile' : IDL.Func([IDL.Nat], [], []),
  'deleteObligation' : IDL.Func([IDL.Nat], [], []),
  'deleteTag' : IDL.Func([IDL.Text], [], []),
  'deleteTimelineEvent' : IDL.Func([IDL.Nat], [], []),
  'getAllTags' : IDL.Func([], [IDL.Vec(ContractTag)], ['query']),
  'getApprovalStep' : IDL.Func([IDL.Nat], [IDL.Opt(ApprovalStep)], ['query']),
  'getApprovalStepsByWorkflow' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ApprovalStep)],
      ['query'],
    ),
  'getApprovalWorkflow' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ApprovalWorkflow)],
      ['query'],
    ),
  'getApprovalWorkflowsByContract' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ApprovalWorkflow)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContract' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], ['query']),
  'getContractsByCounterparty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Contract)],
      ['query'],
    ),
  'getContractsByStatus' : IDL.Func(
      [ContractStatus],
      [IDL.Vec(Contract)],
      ['query'],
    ),
  'getCounterparty' : IDL.Func([IDL.Text], [IDL.Opt(Counterparty)], ['query']),
  'getEventsByContract' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimelineEvent)],
      ['query'],
    ),
  'getExpiringContracts' : IDL.Func([IDL.Int], [IDL.Vec(Contract)], ['query']),
  'getFile' : IDL.Func([IDL.Nat], [IDL.Opt(FileReference)], ['query']),
  'getObligation' : IDL.Func([IDL.Nat], [IDL.Opt(Obligation)], ['query']),
  'getObligationsByContract' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Obligation)],
      ['query'],
    ),
  'getObligationsByStatus' : IDL.Func(
      [ObligationStatus],
      [IDL.Vec(Obligation)],
      ['query'],
    ),
  'getOverdueObligations' : IDL.Func([], [IDL.Vec(Obligation)], ['query']),
  'getRecentEvents' : IDL.Func([IDL.Nat], [IDL.Vec(TimelineEvent)], ['query']),
  'getTag' : IDL.Func([IDL.Text], [IDL.Opt(ContractTag)], ['query']),
  'getTimelineEvent' : IDL.Func([IDL.Nat], [IDL.Opt(TimelineEvent)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'listCounterparties' : IDL.Func([], [IDL.Vec(Counterparty)], ['query']),
  'listFiles' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchContracts' : IDL.Func([IDL.Text], [IDL.Vec(Contract)], ['query']),
  'updateApprovalStepStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'skipped' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateApprovalWorkflowStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateContract' : IDL.Func([IDL.Text, ContractInput], [], []),
  'updateCounterparty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CounterpartyType,
        CounterpartyStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        RiskLevel,
      ],
      [],
      [],
    ),
  'updateObligation' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        ObligationStatus,
        Priority,
      ],
      [],
      [],
    ),
  'updateTag' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateTimelineEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContractStatus = IDL.Variant({
    'active' : IDL.Null,
    'terminated' : IDL.Null,
    'expired' : IDL.Null,
    'underReview' : IDL.Null,
    'draft' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ContractInput = IDL.Record({
    'status' : ContractStatus,
    'endDate' : IDL.Int,
    'value' : IDL.Float64,
    'createdBy' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'counterpartyId' : IDL.Text,
    'autoRenew' : IDL.Bool,
    'department' : IDL.Text,
    'riskLevel' : RiskLevel,
    'renewalDate' : IDL.Opt(IDL.Int),
    'startDate' : IDL.Int,
  });
  const CounterpartyType = IDL.Variant({
    'client' : IDL.Null,
    'internal' : IDL.Null,
    'regulator' : IDL.Null,
    'vendor' : IDL.Null,
    'partner' : IDL.Null,
  });
  const CounterpartyStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'blacklisted' : IDL.Null,
  });
  const ObligationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
    'waived' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ContractTag = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'usageCount' : IDL.Nat,
  });
  const ApprovalStep = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'skipped' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'approverRole' : IDL.Text,
    'stepOrder' : IDL.Nat,
    'comments' : IDL.Opt(IDL.Text),
    'decidedAt' : IDL.Opt(IDL.Int),
    'workflowId' : IDL.Nat,
  });
  const ApprovalWorkflow = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'contractId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Contract = IDL.Record({
    'id' : IDL.Text,
    'status' : ContractStatus,
    'endDate' : IDL.Int,
    'value' : IDL.Float64,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'currency' : IDL.Text,
    'counterpartyId' : IDL.Text,
    'autoRenew' : IDL.Bool,
    'department' : IDL.Text,
    'riskLevel' : RiskLevel,
    'renewalDate' : IDL.Opt(IDL.Int),
    'startDate' : IDL.Int,
  });
  const Counterparty = IDL.Record({
    'id' : IDL.Text,
    'status' : CounterpartyStatus,
    'contactName' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'counterpartyType' : CounterpartyType,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'riskLevel' : RiskLevel,
  });
  const TimelineEvent = IDL.Record({
    'id' : IDL.Nat,
    'metadata' : IDL.Opt(IDL.Text),
    'responsibleParty' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'contractId' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileReference = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const Obligation = IDL.Record({
    'id' : IDL.Nat,
    'status' : ObligationStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'priority' : Priority,
    'contractId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createApprovalStep' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'createApprovalWorkflow' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createContract' : IDL.Func([IDL.Text, ContractInput], [], []),
    'createCounterparty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CounterpartyType,
          CounterpartyStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          RiskLevel,
        ],
        [],
        [],
      ),
    'createObligation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          ObligationStatus,
          Priority,
        ],
        [],
        [],
      ),
    'createTag' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createTimelineEvent' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'deleteApprovalStep' : IDL.Func([IDL.Nat], [], []),
    'deleteApprovalWorkflow' : IDL.Func([IDL.Nat], [], []),
    'deleteContract' : IDL.Func([IDL.Text], [], []),
    'deleteCounterparty' : IDL.Func([IDL.Text], [], []),
    'deleteFile' : IDL.Func([IDL.Nat], [], []),
    'deleteObligation' : IDL.Func([IDL.Nat], [], []),
    'deleteTag' : IDL.Func([IDL.Text], [], []),
    'deleteTimelineEvent' : IDL.Func([IDL.Nat], [], []),
    'getAllTags' : IDL.Func([], [IDL.Vec(ContractTag)], ['query']),
    'getApprovalStep' : IDL.Func([IDL.Nat], [IDL.Opt(ApprovalStep)], ['query']),
    'getApprovalStepsByWorkflow' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ApprovalStep)],
        ['query'],
      ),
    'getApprovalWorkflow' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ApprovalWorkflow)],
        ['query'],
      ),
    'getApprovalWorkflowsByContract' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ApprovalWorkflow)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContract' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], ['query']),
    'getContractsByCounterparty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Contract)],
        ['query'],
      ),
    'getContractsByStatus' : IDL.Func(
        [ContractStatus],
        [IDL.Vec(Contract)],
        ['query'],
      ),
    'getCounterparty' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Counterparty)],
        ['query'],
      ),
    'getEventsByContract' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'getExpiringContracts' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Contract)],
        ['query'],
      ),
    'getFile' : IDL.Func([IDL.Nat], [IDL.Opt(FileReference)], ['query']),
    'getObligation' : IDL.Func([IDL.Nat], [IDL.Opt(Obligation)], ['query']),
    'getObligationsByContract' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Obligation)],
        ['query'],
      ),
    'getObligationsByStatus' : IDL.Func(
        [ObligationStatus],
        [IDL.Vec(Obligation)],
        ['query'],
      ),
    'getOverdueObligations' : IDL.Func([], [IDL.Vec(Obligation)], ['query']),
    'getRecentEvents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimelineEvent)],
        ['query'],
      ),
    'getTag' : IDL.Func([IDL.Text], [IDL.Opt(ContractTag)], ['query']),
    'getTimelineEvent' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TimelineEvent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'listCounterparties' : IDL.Func([], [IDL.Vec(Counterparty)], ['query']),
    'listFiles' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchContracts' : IDL.Func([IDL.Text], [IDL.Vec(Contract)], ['query']),
    'updateApprovalStepStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'skipped' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateApprovalWorkflowStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateContract' : IDL.Func([IDL.Text, ContractInput], [], []),
    'updateCounterparty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CounterpartyType,
          CounterpartyStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          RiskLevel,
        ],
        [],
        [],
      ),
    'updateObligation' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          ObligationStatus,
          Priority,
        ],
        [],
        [],
      ),
    'updateTag' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateTimelineEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };