/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApprovalStep {
  'status' : { 'pending' : null } |
    { 'skipped' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'approverRole' : string,
  'stepOrder' : bigint,
  'comments' : [] | [string],
  'decidedAt' : [] | [bigint],
  'workflowId' : bigint,
}
export interface ApprovalWorkflow {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null } |
    { 'inProgress' : null },
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'contractId' : string,
}
export interface Contract {
  'id' : string,
  'status' : ContractStatus,
  'endDate' : bigint,
  'value' : number,
  'createdAt' : bigint,
  'createdBy' : string,
  'tags' : Array<string>,
  'description' : string,
  'updatedAt' : bigint,
  'currency' : string,
  'counterpartyId' : string,
  'autoRenew' : boolean,
  'department' : string,
  'riskLevel' : RiskLevel,
  'renewalDate' : [] | [bigint],
  'startDate' : bigint,
}
export interface ContractInput {
  'status' : ContractStatus,
  'endDate' : bigint,
  'value' : number,
  'createdBy' : string,
  'tags' : Array<string>,
  'description' : string,
  'currency' : string,
  'counterpartyId' : string,
  'autoRenew' : boolean,
  'department' : string,
  'riskLevel' : RiskLevel,
  'renewalDate' : [] | [bigint],
  'startDate' : bigint,
}
export type ContractStatus = { 'active' : null } |
  { 'terminated' : null } |
  { 'expired' : null } |
  { 'underReview' : null } |
  { 'draft' : null };
export interface ContractTag {
  'name' : string,
  'color' : string,
  'usageCount' : bigint,
}
export interface Counterparty {
  'id' : string,
  'status' : CounterpartyStatus,
  'contactName' : string,
  'country' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'updatedAt' : bigint,
  'counterpartyType' : CounterpartyType,
  'address' : string,
  'phone' : string,
  'riskLevel' : RiskLevel,
}
export type CounterpartyStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'blacklisted' : null };
export type CounterpartyType = { 'client' : null } |
  { 'internal' : null } |
  { 'regulator' : null } |
  { 'vendor' : null } |
  { 'partner' : null };
export type ExternalBlob = Uint8Array;
export interface FileReference {
  'id' : bigint,
  'blob' : ExternalBlob,
  'name' : string,
  'uploadedAt' : bigint,
}
export interface Obligation {
  'id' : bigint,
  'status' : ObligationStatus,
  'title' : string,
  'assignedTo' : string,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'priority' : Priority,
  'contractId' : string,
}
export type ObligationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'overdue' : null } |
  { 'waived' : null } |
  { 'inProgress' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface TimelineEvent {
  'id' : bigint,
  'metadata' : [] | [string],
  'responsibleParty' : string,
  'description' : string,
  'timestamp' : bigint,
  'contractId' : [] | [string],
  'eventType' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createApprovalStep' : ActorMethod<[bigint, bigint, string], undefined>,
  'createApprovalWorkflow' : ActorMethod<[string], bigint>,
  'createContract' : ActorMethod<[string, ContractInput], undefined>,
  'createCounterparty' : ActorMethod<
    [
      string,
      string,
      CounterpartyType,
      CounterpartyStatus,
      string,
      string,
      string,
      string,
      string,
      RiskLevel,
    ],
    undefined
  >,
  'createObligation' : ActorMethod<
    [string, string, string, string, bigint, ObligationStatus, Priority],
    undefined
  >,
  'createTag' : ActorMethod<[string, string], undefined>,
  'createTimelineEvent' : ActorMethod<
    [[] | [string], string, string, string, [] | [string]],
    undefined
  >,
  'deleteApprovalStep' : ActorMethod<[bigint], undefined>,
  'deleteApprovalWorkflow' : ActorMethod<[bigint], undefined>,
  'deleteContract' : ActorMethod<[string], undefined>,
  'deleteCounterparty' : ActorMethod<[string], undefined>,
  'deleteFile' : ActorMethod<[bigint], undefined>,
  'deleteObligation' : ActorMethod<[bigint], undefined>,
  'deleteTag' : ActorMethod<[string], undefined>,
  'deleteTimelineEvent' : ActorMethod<[bigint], undefined>,
  'getAllTags' : ActorMethod<[], Array<ContractTag>>,
  'getApprovalStep' : ActorMethod<[bigint], [] | [ApprovalStep]>,
  'getApprovalStepsByWorkflow' : ActorMethod<[bigint], Array<ApprovalStep>>,
  'getApprovalWorkflow' : ActorMethod<[bigint], [] | [ApprovalWorkflow]>,
  'getApprovalWorkflowsByContract' : ActorMethod<
    [string],
    Array<ApprovalWorkflow>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContract' : ActorMethod<[string], [] | [Contract]>,
  'getContractsByCounterparty' : ActorMethod<[string], Array<Contract>>,
  'getContractsByStatus' : ActorMethod<[ContractStatus], Array<Contract>>,
  'getCounterparty' : ActorMethod<[string], [] | [Counterparty]>,
  'getEventsByContract' : ActorMethod<[string], Array<TimelineEvent>>,
  'getExpiringContracts' : ActorMethod<[bigint], Array<Contract>>,
  'getFile' : ActorMethod<[bigint], [] | [FileReference]>,
  'getObligation' : ActorMethod<[bigint], [] | [Obligation]>,
  'getObligationsByContract' : ActorMethod<[string], Array<Obligation>>,
  'getObligationsByStatus' : ActorMethod<[ObligationStatus], Array<Obligation>>,
  'getOverdueObligations' : ActorMethod<[], Array<Obligation>>,
  'getRecentEvents' : ActorMethod<[bigint], Array<TimelineEvent>>,
  'getTag' : ActorMethod<[string], [] | [ContractTag]>,
  'getTimelineEvent' : ActorMethod<[bigint], [] | [TimelineEvent]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContracts' : ActorMethod<[], Array<Contract>>,
  'listCounterparties' : ActorMethod<[], Array<Counterparty>>,
  'listFiles' : ActorMethod<[], Array<FileReference>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchContracts' : ActorMethod<[string], Array<Contract>>,
  'updateApprovalStepStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'skipped' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
      [] | [string],
    ],
    undefined
  >,
  'updateApprovalWorkflowStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'approved' : null } |
        { 'rejected' : null } |
        { 'inProgress' : null },
    ],
    undefined
  >,
  'updateContract' : ActorMethod<[string, ContractInput], undefined>,
  'updateCounterparty' : ActorMethod<
    [
      string,
      string,
      CounterpartyType,
      CounterpartyStatus,
      string,
      string,
      string,
      string,
      string,
      RiskLevel,
    ],
    undefined
  >,
  'updateObligation' : ActorMethod<
    [bigint, string, string, string, bigint, ObligationStatus, Priority],
    undefined
  >,
  'updateTag' : ActorMethod<[string, string, bigint], undefined>,
  'updateTimelineEvent' : ActorMethod<
    [bigint, string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'uploadFile' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];