/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContractTag {
    name: string;
    color: string;
    usageCount: bigint;
}
export interface Obligation {
    id: bigint;
    status: ObligationStatus;
    title: string;
    assignedTo: string;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    updatedAt: bigint;
    priority: Priority;
    contractId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ApprovalWorkflow {
    id: bigint;
    status: Variant_pending_approved_rejected_inProgress;
    createdAt: bigint;
    updatedAt: bigint;
    contractId: string;
}
export interface ApprovalStep {
    status: Variant_pending_skipped_approved_rejected;
    approverRole: string;
    stepOrder: bigint;
    comments?: string;
    decidedAt?: bigint;
    workflowId: bigint;
}
export interface TimelineEvent {
    id: bigint;
    metadata?: string;
    responsibleParty: string;
    description: string;
    timestamp: bigint;
    contractId?: string;
    eventType: string;
}
export interface Counterparty {
    id: string;
    status: CounterpartyStatus;
    contactName: string;
    country: string;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    counterpartyType: CounterpartyType;
    address: string;
    phone: string;
    riskLevel: RiskLevel;
}
export interface ContractInput {
    status: ContractStatus;
    endDate: bigint;
    value: number;
    createdBy: string;
    tags: Array<string>;
    description: string;
    currency: string;
    counterpartyId: string;
    autoRenew: boolean;
    department: string;
    riskLevel: RiskLevel;
    renewalDate?: bigint;
    startDate: bigint;
}
export interface FileReference {
    id: bigint;
    blob: ExternalBlob;
    name: string;
    uploadedAt: bigint;
}
export interface Contract {
    id: string;
    status: ContractStatus;
    endDate: bigint;
    value: number;
    createdAt: bigint;
    createdBy: string;
    tags: Array<string>;
    description: string;
    updatedAt: bigint;
    currency: string;
    counterpartyId: string;
    autoRenew: boolean;
    department: string;
    riskLevel: RiskLevel;
    renewalDate?: bigint;
    startDate: bigint;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ContractStatus {
    active = "active",
    terminated = "terminated",
    expired = "expired",
    underReview = "underReview",
    draft = "draft"
}
export enum CounterpartyStatus {
    active = "active",
    inactive = "inactive",
    blacklisted = "blacklisted"
}
export enum CounterpartyType {
    client = "client",
    internal = "internal",
    regulator = "regulator",
    vendor = "vendor",
    partner = "partner"
}
export enum ObligationStatus {
    pending = "pending",
    completed = "completed",
    overdue = "overdue",
    waived = "waived",
    inProgress = "inProgress"
}
export enum Priority {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected_inProgress {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    inProgress = "inProgress"
}
export enum Variant_pending_skipped_approved_rejected {
    pending = "pending",
    skipped = "skipped",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createApprovalStep(workflowId: bigint, stepOrder: bigint, approverRole: string): Promise<void>;
    createApprovalWorkflow(contractId: string): Promise<bigint>;
    createContract(id: string, input: ContractInput): Promise<void>;
    createCounterparty(id: string, name: string, counterpartyType: CounterpartyType, status: CounterpartyStatus, email: string, phone: string, address: string, country: string, contactName: string, riskLevel: RiskLevel): Promise<void>;
    createObligation(contractId: string, title: string, description: string, assignedTo: string, dueDate: bigint, status: ObligationStatus, priority: Priority): Promise<void>;
    createTag(name: string, color: string): Promise<void>;
    createTimelineEvent(contractId: string | null, eventType: string, description: string, responsibleParty: string, metadata: string | null): Promise<void>;
    deleteApprovalStep(workflowId: bigint): Promise<void>;
    deleteApprovalWorkflow(id: bigint): Promise<void>;
    deleteContract(id: string): Promise<void>;
    deleteCounterparty(id: string): Promise<void>;
    deleteFile(id: bigint): Promise<void>;
    deleteObligation(id: bigint): Promise<void>;
    deleteTag(name: string): Promise<void>;
    deleteTimelineEvent(id: bigint): Promise<void>;
    getAllTags(): Promise<Array<ContractTag>>;
    getApprovalStep(workflowId: bigint): Promise<ApprovalStep | null>;
    getApprovalStepsByWorkflow(workflowId: bigint): Promise<Array<ApprovalStep>>;
    getApprovalWorkflow(id: bigint): Promise<ApprovalWorkflow | null>;
    getApprovalWorkflowsByContract(contractId: string): Promise<Array<ApprovalWorkflow>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContract(id: string): Promise<Contract | null>;
    getContractsByCounterparty(counterpartyId: string): Promise<Array<Contract>>;
    getContractsByStatus(status: ContractStatus): Promise<Array<Contract>>;
    getCounterparty(id: string): Promise<Counterparty | null>;
    getEventsByContract(contractId: string): Promise<Array<TimelineEvent>>;
    getExpiringContracts(days: bigint): Promise<Array<Contract>>;
    getFile(id: bigint): Promise<FileReference | null>;
    getObligation(id: bigint): Promise<Obligation | null>;
    getObligationsByContract(contractId: string): Promise<Array<Obligation>>;
    getObligationsByStatus(status: ObligationStatus): Promise<Array<Obligation>>;
    getOverdueObligations(): Promise<Array<Obligation>>;
    getRecentEvents(limit: bigint): Promise<Array<TimelineEvent>>;
    getTag(name: string): Promise<ContractTag | null>;
    getTimelineEvent(id: bigint): Promise<TimelineEvent | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listContracts(): Promise<Array<Contract>>;
    listCounterparties(): Promise<Array<Counterparty>>;
    listFiles(): Promise<Array<FileReference>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchContracts(searchTerm: string): Promise<Array<Contract>>;
    updateApprovalStepStatus(workflowId: bigint, status: Variant_pending_skipped_approved_rejected, comments: string | null): Promise<void>;
    updateApprovalWorkflowStatus(id: bigint, status: Variant_pending_approved_rejected_inProgress): Promise<void>;
    updateContract(id: string, input: ContractInput): Promise<void>;
    updateCounterparty(id: string, name: string, counterpartyType: CounterpartyType, status: CounterpartyStatus, email: string, phone: string, address: string, country: string, contactName: string, riskLevel: RiskLevel): Promise<void>;
    updateObligation(id: bigint, title: string, description: string, assignedTo: string, dueDate: bigint, status: ObligationStatus, priority: Priority): Promise<void>;
    updateTag(name: string, color: string, usageCount: bigint): Promise<void>;
    updateTimelineEvent(id: bigint, eventType: string, description: string, responsibleParty: string, contractId: string | null, metadata: string | null): Promise<void>;
    uploadFile(name: string, blob: ExternalBlob): Promise<void>;
}
import type { ApprovalStep as _ApprovalStep, ApprovalWorkflow as _ApprovalWorkflow, Contract as _Contract, ContractInput as _ContractInput, ContractStatus as _ContractStatus, ContractTag as _ContractTag, Counterparty as _Counterparty, CounterpartyStatus as _CounterpartyStatus, CounterpartyType as _CounterpartyType, ExternalBlob as _ExternalBlob, FileReference as _FileReference, Obligation as _Obligation, ObligationStatus as _ObligationStatus, Priority as _Priority, RiskLevel as _RiskLevel, TimelineEvent as _TimelineEvent, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createApprovalStep(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createApprovalStep(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApprovalStep(arg0, arg1, arg2);
            return result;
        }
    }
    async createApprovalWorkflow(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createApprovalWorkflow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApprovalWorkflow(arg0);
            return result;
        }
    }
    async createContract(arg0: string, arg1: ContractInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, to_candid_ContractInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, to_candid_ContractInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCounterparty(arg0: string, arg1: string, arg2: CounterpartyType, arg3: CounterpartyStatus, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: RiskLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCounterparty(arg0, arg1, to_candid_CounterpartyType_n16(this._uploadFile, this._downloadFile, arg2), to_candid_CounterpartyStatus_n18(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_RiskLevel_n14(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCounterparty(arg0, arg1, to_candid_CounterpartyType_n16(this._uploadFile, this._downloadFile, arg2), to_candid_CounterpartyStatus_n18(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_RiskLevel_n14(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async createObligation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: ObligationStatus, arg6: Priority): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createObligation(arg0, arg1, arg2, arg3, arg4, to_candid_ObligationStatus_n20(this._uploadFile, this._downloadFile, arg5), to_candid_Priority_n22(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createObligation(arg0, arg1, arg2, arg3, arg4, to_candid_ObligationStatus_n20(this._uploadFile, this._downloadFile, arg5), to_candid_Priority_n22(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createTag(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTag(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTag(arg0, arg1);
            return result;
        }
    }
    async createTimelineEvent(arg0: string | null, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTimelineEvent(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTimelineEvent(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteApprovalStep(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApprovalStep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApprovalStep(arg0);
            return result;
        }
    }
    async deleteApprovalWorkflow(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApprovalWorkflow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApprovalWorkflow(arg0);
            return result;
        }
    }
    async deleteContract(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContract(arg0);
            return result;
        }
    }
    async deleteCounterparty(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCounterparty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCounterparty(arg0);
            return result;
        }
    }
    async deleteFile(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteObligation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteObligation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteObligation(arg0);
            return result;
        }
    }
    async deleteTag(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTag(arg0);
            return result;
        }
    }
    async deleteTimelineEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimelineEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimelineEvent(arg0);
            return result;
        }
    }
    async getAllTags(): Promise<Array<ContractTag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getApprovalStep(arg0: bigint): Promise<ApprovalStep | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovalStep(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovalStep(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovalStepsByWorkflow(arg0: bigint): Promise<Array<ApprovalStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovalStepsByWorkflow(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovalStepsByWorkflow(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovalWorkflow(arg0: bigint): Promise<ApprovalWorkflow | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovalWorkflow(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovalWorkflow(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovalWorkflowsByContract(arg0: string): Promise<Array<ApprovalWorkflow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovalWorkflowsByContract(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovalWorkflowsByContract(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContract(arg0: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractsByCounterparty(arg0: string): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractsByCounterparty(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractsByCounterparty(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractsByStatus(arg0: ContractStatus): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractsByStatus(to_candid_ContractStatus_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractsByStatus(to_candid_ContractStatus_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCounterparty(arg0: string): Promise<Counterparty | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCounterparty(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCounterparty(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByContract(arg0: string): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByContract(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByContract(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpiringContracts(arg0: bigint): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiringContracts(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiringContracts(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFile(arg0: bigint): Promise<FileReference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFile(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFile(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getObligation(arg0: bigint): Promise<Obligation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getObligation(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObligation(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getObligationsByContract(arg0: string): Promise<Array<Obligation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getObligationsByContract(arg0);
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObligationsByContract(arg0);
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getObligationsByStatus(arg0: ObligationStatus): Promise<Array<Obligation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getObligationsByStatus(to_candid_ObligationStatus_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObligationsByStatus(to_candid_ObligationStatus_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueObligations(): Promise<Array<Obligation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueObligations();
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueObligations();
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentEvents(arg0: bigint): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentEvents(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentEvents(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTag(arg0: string): Promise<ContractTag | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTag(arg0);
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTag(arg0);
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimelineEvent(arg0: bigint): Promise<TimelineEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimelineEvent(arg0);
                return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimelineEvent(arg0);
            return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContracts();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContracts();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCounterparties(): Promise<Array<Counterparty>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCounterparties();
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCounterparties();
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFiles(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFiles();
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFiles();
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchContracts(arg0: string): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchContracts(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchContracts(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateApprovalStepStatus(arg0: bigint, arg1: Variant_pending_skipped_approved_rejected, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApprovalStepStatus(arg0, to_candid_variant_n72(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApprovalStepStatus(arg0, to_candid_variant_n72(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateApprovalWorkflowStatus(arg0: bigint, arg1: Variant_pending_approved_rejected_inProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApprovalWorkflowStatus(arg0, to_candid_variant_n73(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApprovalWorkflowStatus(arg0, to_candid_variant_n73(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateContract(arg0: string, arg1: ContractInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0, to_candid_ContractInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0, to_candid_ContractInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCounterparty(arg0: string, arg1: string, arg2: CounterpartyType, arg3: CounterpartyStatus, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: RiskLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCounterparty(arg0, arg1, to_candid_CounterpartyType_n16(this._uploadFile, this._downloadFile, arg2), to_candid_CounterpartyStatus_n18(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_RiskLevel_n14(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCounterparty(arg0, arg1, to_candid_CounterpartyType_n16(this._uploadFile, this._downloadFile, arg2), to_candid_CounterpartyStatus_n18(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_RiskLevel_n14(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async updateObligation(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: ObligationStatus, arg6: Priority): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateObligation(arg0, arg1, arg2, arg3, arg4, to_candid_ObligationStatus_n20(this._uploadFile, this._downloadFile, arg5), to_candid_Priority_n22(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateObligation(arg0, arg1, arg2, arg3, arg4, to_candid_ObligationStatus_n20(this._uploadFile, this._downloadFile, arg5), to_candid_Priority_n22(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateTag(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTag(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTag(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTimelineEvent(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimelineEvent(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimelineEvent(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async uploadFile(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n74(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n74(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStep_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStep): ApprovalStep {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalWorkflow_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalWorkflow): ApprovalWorkflow {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ContractStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractStatus): ContractStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Contract_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Contract {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_CounterpartyStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CounterpartyStatus): CounterpartyStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_CounterpartyType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CounterpartyType): CounterpartyType {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Counterparty_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Counterparty): Counterparty {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileReference_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileReference): Promise<FileReference> {
    return await from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_ObligationStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObligationStatus): ObligationStatus {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Obligation_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Obligation): Obligation {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineEvent_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEvent): TimelineEvent {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApprovalStep]): ApprovalStep | null {
    return value.length === 0 ? null : from_candid_ApprovalStep_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApprovalWorkflow]): ApprovalWorkflow | null {
    return value.length === 0 ? null : from_candid_ApprovalWorkflow_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contract]): Contract | null {
    return value.length === 0 ? null : from_candid_Contract_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Counterparty]): Counterparty | null {
    return value.length === 0 ? null : from_candid_Counterparty_n48(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileReference]): Promise<FileReference | null> {
    return value.length === 0 ? null : await from_candid_FileReference_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Obligation]): Obligation | null {
    return value.length === 0 ? null : from_candid_Obligation_n62(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContractTag]): ContractTag | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimelineEvent]): TimelineEvent | null {
    return value.length === 0 ? null : from_candid_TimelineEvent_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        skipped: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    approverRole: string;
    stepOrder: bigint;
    comments: [] | [string];
    decidedAt: [] | [bigint];
    workflowId: bigint;
}): {
    status: Variant_pending_skipped_approved_rejected;
    approverRole: string;
    stepOrder: bigint;
    comments?: string;
    decidedAt?: bigint;
    workflowId: bigint;
} {
    return {
        status: from_candid_variant_n27(_uploadFile, _downloadFile, value.status),
        approverRole: value.approverRole,
        stepOrder: value.stepOrder,
        comments: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.comments)),
        decidedAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.decidedAt)),
        workflowId: value.workflowId
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    } | {
        inProgress: null;
    };
    createdAt: bigint;
    updatedAt: bigint;
    contractId: string;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected_inProgress;
    createdAt: bigint;
    updatedAt: bigint;
    contractId: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        contractId: value.contractId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ContractStatus;
    endDate: bigint;
    value: number;
    createdAt: bigint;
    createdBy: string;
    tags: Array<string>;
    description: string;
    updatedAt: bigint;
    currency: string;
    counterpartyId: string;
    autoRenew: boolean;
    department: string;
    riskLevel: _RiskLevel;
    renewalDate: [] | [bigint];
    startDate: bigint;
}): {
    id: string;
    status: ContractStatus;
    endDate: bigint;
    value: number;
    createdAt: bigint;
    createdBy: string;
    tags: Array<string>;
    description: string;
    updatedAt: bigint;
    currency: string;
    counterpartyId: string;
    autoRenew: boolean;
    department: string;
    riskLevel: RiskLevel;
    renewalDate?: bigint;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ContractStatus_n42(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        value: value.value,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        tags: value.tags,
        description: value.description,
        updatedAt: value.updatedAt,
        currency: value.currency,
        counterpartyId: value.counterpartyId,
        autoRenew: value.autoRenew,
        department: value.department,
        riskLevel: from_candid_RiskLevel_n44(_uploadFile, _downloadFile, value.riskLevel),
        renewalDate: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.renewalDate)),
        startDate: value.startDate
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CounterpartyStatus;
    contactName: string;
    country: string;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    counterpartyType: _CounterpartyType;
    address: string;
    phone: string;
    riskLevel: _RiskLevel;
}): {
    id: string;
    status: CounterpartyStatus;
    contactName: string;
    country: string;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    counterpartyType: CounterpartyType;
    address: string;
    phone: string;
    riskLevel: RiskLevel;
} {
    return {
        id: value.id,
        status: from_candid_CounterpartyStatus_n50(_uploadFile, _downloadFile, value.status),
        contactName: value.contactName,
        country: value.country,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        counterpartyType: from_candid_CounterpartyType_n52(_uploadFile, _downloadFile, value.counterpartyType),
        address: value.address,
        phone: value.phone,
        riskLevel: from_candid_RiskLevel_n44(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    metadata: [] | [string];
    responsibleParty: string;
    description: string;
    timestamp: bigint;
    contractId: [] | [string];
    eventType: string;
}): {
    id: bigint;
    metadata?: string;
    responsibleParty: string;
    description: string;
    timestamp: bigint;
    contractId?: string;
    eventType: string;
} {
    return {
        id: value.id,
        metadata: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.metadata)),
        responsibleParty: value.responsibleParty,
        description: value.description,
        timestamp: value.timestamp,
        contractId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.contractId)),
        eventType: value.eventType
    };
}
async function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    name: string;
    uploadedAt: bigint;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    name: string;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n60(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ObligationStatus;
    title: string;
    assignedTo: string;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    updatedAt: bigint;
    priority: _Priority;
    contractId: string;
}): {
    id: bigint;
    status: ObligationStatus;
    title: string;
    assignedTo: string;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    updatedAt: bigint;
    priority: Priority;
    contractId: string;
} {
    return {
        id: value.id,
        status: from_candid_ObligationStatus_n64(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: value.assignedTo,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        updatedAt: value.updatedAt,
        priority: from_candid_Priority_n66(_uploadFile, _downloadFile, value.priority),
        contractId: value.contractId
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    skipped: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_skipped_approved_rejected {
    return "pending" in value ? Variant_pending_skipped_approved_rejected.pending : "skipped" in value ? Variant_pending_skipped_approved_rejected.skipped : "approved" in value ? Variant_pending_skipped_approved_rejected.approved : "rejected" in value ? Variant_pending_skipped_approved_rejected.rejected : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    inProgress: null;
}): Variant_pending_approved_rejected_inProgress {
    return "pending" in value ? Variant_pending_approved_rejected_inProgress.pending : "approved" in value ? Variant_pending_approved_rejected_inProgress.approved : "rejected" in value ? Variant_pending_approved_rejected_inProgress.rejected : "inProgress" in value ? Variant_pending_approved_rejected_inProgress.inProgress : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    terminated: null;
} | {
    expired: null;
} | {
    underReview: null;
} | {
    draft: null;
}): ContractStatus {
    return "active" in value ? ContractStatus.active : "terminated" in value ? ContractStatus.terminated : "expired" in value ? ContractStatus.expired : "underReview" in value ? ContractStatus.underReview : "draft" in value ? ContractStatus.draft : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "critical" in value ? Priority.critical : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    blacklisted: null;
}): CounterpartyStatus {
    return "active" in value ? CounterpartyStatus.active : "inactive" in value ? CounterpartyStatus.inactive : "blacklisted" in value ? CounterpartyStatus.blacklisted : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    internal: null;
} | {
    regulator: null;
} | {
    vendor: null;
} | {
    partner: null;
}): CounterpartyType {
    return "client" in value ? CounterpartyType.client : "internal" in value ? CounterpartyType.internal : "regulator" in value ? CounterpartyType.regulator : "vendor" in value ? CounterpartyType.vendor : "partner" in value ? CounterpartyType.partner : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
} | {
    waived: null;
} | {
    inProgress: null;
}): ObligationStatus {
    return "pending" in value ? ObligationStatus.pending : "completed" in value ? ObligationStatus.completed : "overdue" in value ? ObligationStatus.overdue : "waived" in value ? ObligationStatus.waived : "inProgress" in value ? ObligationStatus.inProgress : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalStep>): Array<ApprovalStep> {
    return value.map((x)=>from_candid_ApprovalStep_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalWorkflow>): Array<ApprovalWorkflow> {
    return value.map((x)=>from_candid_ApprovalWorkflow_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contract>): Array<Contract> {
    return value.map((x)=>from_candid_Contract_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimelineEvent>): Array<TimelineEvent> {
    return value.map((x)=>from_candid_TimelineEvent_n55(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Obligation>): Array<Obligation> {
    return value.map((x)=>from_candid_Obligation_n62(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Counterparty>): Array<Counterparty> {
    return value.map((x)=>from_candid_Counterparty_n48(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileReference>): Promise<Array<FileReference>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileReference_n58(_uploadFile, _downloadFile, x)));
}
function to_candid_ContractInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractInput): _ContractInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ContractStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractStatus): _ContractStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_CounterpartyStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CounterpartyStatus): _CounterpartyStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_CounterpartyType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CounterpartyType): _CounterpartyType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ObligationStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ObligationStatus): _ObligationStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ContractStatus;
    endDate: bigint;
    value: number;
    createdBy: string;
    tags: Array<string>;
    description: string;
    currency: string;
    counterpartyId: string;
    autoRenew: boolean;
    department: string;
    riskLevel: RiskLevel;
    renewalDate?: bigint;
    startDate: bigint;
}): {
    status: _ContractStatus;
    endDate: bigint;
    value: number;
    createdBy: string;
    tags: Array<string>;
    description: string;
    currency: string;
    counterpartyId: string;
    autoRenew: boolean;
    department: string;
    riskLevel: _RiskLevel;
    renewalDate: [] | [bigint];
    startDate: bigint;
} {
    return {
        status: to_candid_ContractStatus_n12(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        value: value.value,
        createdBy: value.createdBy,
        tags: value.tags,
        description: value.description,
        currency: value.currency,
        counterpartyId: value.counterpartyId,
        autoRenew: value.autoRenew,
        department: value.department,
        riskLevel: to_candid_RiskLevel_n14(_uploadFile, _downloadFile, value.riskLevel),
        renewalDate: value.renewalDate ? candid_some(value.renewalDate) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractStatus): {
    active: null;
} | {
    terminated: null;
} | {
    expired: null;
} | {
    underReview: null;
} | {
    draft: null;
} {
    return value == ContractStatus.active ? {
        active: null
    } : value == ContractStatus.terminated ? {
        terminated: null
    } : value == ContractStatus.expired ? {
        expired: null
    } : value == ContractStatus.underReview ? {
        underReview: null
    } : value == ContractStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.critical ? {
        critical: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CounterpartyType): {
    client: null;
} | {
    internal: null;
} | {
    regulator: null;
} | {
    vendor: null;
} | {
    partner: null;
} {
    return value == CounterpartyType.client ? {
        client: null
    } : value == CounterpartyType.internal ? {
        internal: null
    } : value == CounterpartyType.regulator ? {
        regulator: null
    } : value == CounterpartyType.vendor ? {
        vendor: null
    } : value == CounterpartyType.partner ? {
        partner: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CounterpartyStatus): {
    active: null;
} | {
    inactive: null;
} | {
    blacklisted: null;
} {
    return value == CounterpartyStatus.active ? {
        active: null
    } : value == CounterpartyStatus.inactive ? {
        inactive: null
    } : value == CounterpartyStatus.blacklisted ? {
        blacklisted: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ObligationStatus): {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
} | {
    waived: null;
} | {
    inProgress: null;
} {
    return value == ObligationStatus.pending ? {
        pending: null
    } : value == ObligationStatus.completed ? {
        completed: null
    } : value == ObligationStatus.overdue ? {
        overdue: null
    } : value == ObligationStatus.waived ? {
        waived: null
    } : value == ObligationStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_skipped_approved_rejected): {
    pending: null;
} | {
    skipped: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Variant_pending_skipped_approved_rejected.pending ? {
        pending: null
    } : value == Variant_pending_skipped_approved_rejected.skipped ? {
        skipped: null
    } : value == Variant_pending_skipped_approved_rejected.approved ? {
        approved: null
    } : value == Variant_pending_skipped_approved_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_approved_rejected_inProgress): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} {
    return value == Variant_pending_approved_rejected_inProgress.pending ? {
        pending: null
    } : value == Variant_pending_approved_rejected_inProgress.approved ? {
        approved: null
    } : value == Variant_pending_approved_rejected_inProgress.rejected ? {
        rejected: null
    } : value == Variant_pending_approved_rejected_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
